import streamlit as st

st.write('Hello, *These are the Bond movies I wish to use as my strength!* :sunglasses:')

st.write('1. DR. NO')
st.write('2. FROM RUSSIA WITH LOVE')
st.write('3. GOLDFINGER')
st.write('4. THUNDERBALL')
st.write('5. YOU ONLY LIVE TWICE')
st.write('6. DIAMONDS ARE FOREVER')
st.write('7. ON HER MAJESTYS SECRET SERVICE')
st.write('8. LIVE AND LET DIE')
st.write('9. THE MAN WITH THE GOLDEN GUN')
st.write('10. THE SPY WHO LOVED ME')
st.write('11. MOONRAKER')
st.write('12. FOR YOUR EYES ONLY')
st.write('13. OCTOPUSSY')
st.write('14. A VIEW TO A KILL')
st.write('15. THE LIVING DAYLIGHTS')
st.write('16. LICENSE TO KILL')
st.write('17. GOLDENEYE')
st.write('18. TOMORROW NEVER DIES')
st.write('19. THE WORLD IS NOT ENOUGH')
st.write('20. DIE ANOTHER DAY')
